name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  ai-code-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: AI Code Review
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_light_model: gpt-4o
          openai_heavy_model: gpt-4o
          path_filters: |
            !.github/workflows/**
            src/**
            !**/*.test.ts
            !**/*.test.tsx
            !**/*.spec.ts
            !**/*.spec.tsx
          system_message: |
            You are an expert code reviewer for a Next.js application using PayloadCMS.
            Focus on the following areas:
            1. Performance issues, especially with React components and hooks
            2. Security vulnerabilities in authentication flows
            3. Proper implementation of PPR (Partial Prerendering)
            4. TypeScript type safety
            5. Accessibility issues
            
            Be concise and specific. Provide code examples when suggesting improvements.